version: '3.6'

#volumes:
#  keycloak_postgres_data: {}
#    external: true
#      name: C:\Users\ASUS\kavinda\gitProject\grocery\keycloak\data\postgresql

#volumes:
#  postgres_data:
#    driver: local

services:
  postgres-keycloak:
    image: postgres:9.6-alpine
    container_name: postgres
#    volumes:
#      - type: volume
#        source: /var/lib/postgresql/data
#        target: C:\Users\ASUS\kavinda\gitProject\grocery\keycloak\data\postgresql
#      - C:\Users\ASUS\kavinda\gitProject\grocery\keycloak\data\postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - dev_network

  keycloak:
    image: jboss/keycloak:10.0.2
    container_name: keycloak_10
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    external_links:
      - postgres
    volumes:
      - ./themes/keycloak:/opt/jboss/keycloak/themes/shoping
#      - ./imports:/opt/jboss/keycloak/imports
#    command:
#      - "-b 0.0.0.0"
#      - "-Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    depends_on:
      - postgres-keycloak
    networks:
      - dev_network
networks:
  dev_network: